spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;

rsa:
  public-key: classpath:certs/dev/public.pem
  private-key-path: certs/dev/private.pem.enc

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    hexlet.code: DEBUG

sentry:
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: debug
    minimum-level: debug


##########################
PRIVATE_KEY_PASSWORD: weaKPa55w0rd
PRIVATE_KEY_SALT: c036d7ae55bcaf25
DEFAULT_PASSWORD: qwerty