spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    hexlet.code: DEBUG

sentry:
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: debug
    minimum-level: debug
